[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Marcos Gaeta <marcos.gaeta@sentry.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reduce = "0.1.3"
regex = "1"
